---
- name: Register VM_IP Artifact
  hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Save host data within a Group
    add_host:
      hostname: "{{ vm_ip }}"
      groupname: hardening_servers
    tags:
      - getting_vm_ip

  - name: Wait for SSH to come up
    wait_for: host={{ vm_ip }} port=22 delay=10 timeout=60
    tags:
      - getting_vm_ip

- name: RHEL8 PCI-DSS Hardening
  hosts: hardening_servers
  roles:
     - { role: RedHatOfficial.rhel8_pci_dss }
